### ISSUE TITLE
Separate linting and file loading concerns

### ISSUE THREAD

**Issue by jblazek** [wework/speccy#10]
Currently, the linter is doing file IO to load the rules as well as performing the linting.

It would be easier to test the linter if the lint function accepted an argument with a set of rules rather than a specific ruleset name that gets internally loaded as a file. 

This should help with adding custom rule files, since you could validate the contents of the rules in the loader.

**Comment by philsturgeon** [comment]
@jblazek hey, I've done this over here https://github.com/wework/speccy/pull/31

No custom file loading yet, but that'll be pretty simple to write now. Improved test coverage a bunch too.
