### ISSUE TITLE
Is it possible to validate response schema with speccy tool.

### ISSUE THREAD

**Issue by ShwetaManekari** [wework/speccy#112]
Hello All,
Currently I am able to validate my API specification which is in OpenAPI 3.0 format with default and custom rules. But wanted to validate response too with speccy tool. For example in my specification I have schema's under responses which return data, so I want to validate the schema's with data.
How to do with speccy tool any thoughts?

**Comment by philsturgeon** [comment]
Hey, sorry I'm not sure what you mean? Are you talking about doing something like this? 

https://blog.apisyouwonthate.com/tricking-colleagues-into-writing-documentation-via-contract-testing-206308b47e05

**Comment by philsturgeon** [comment]
JSON Matchers is just a thin assertion layer around a JSON Schema validator.

You can use a JSON Schema validator for whatever language you like: http://json-schema.org/implementations.html

Or you can either use an OpenAPI validator for whatever language you like: http://openapi.tools/
