### ISSUE TITLE
path-keys-no-trailing-slash is being detected on root path

### ISSUE THREAD

**Issue by nesl247** [wework/speccy#134]
## Detailed description

Speccy is detecting a `/` path with `path-keys-no-trailing-slash` as an error. This should be excluded as `/` is a valid path.

## Context

We use the `/` path to show the current timestamp, version, and other misc. information. We should be able to document this, and it is valid OAI as far as I can see.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Node Version: 8.11.3
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 10.14
* Link to your project: private
* Speccy version: 0.8.0
* Ruleset: strict

**Comment by philsturgeon** [comment]
Hey @nesl247 can you test this one out? https://github.com/wework/speccy/pull/137

**Comment by nesl247** [comment]
@philsturgeon It works, thanks!

**Comment by marcokrikke** [comment]
This is broken again:

````
#/paths/~1  R: path-keys-no-trailing-slash  D: paths should not end with a slash
expected '/' not to end with '/' (false negative fail)
````

Is this something you should fix, or should it be fixed in the `oas-linter` definition of `notEndWith`?
