### ISSUE TITLE
Spaces in paths cause errors (breaking change in v0.8.0)

### ISSUE THREAD

**Issue by JamesMessinger** [wework/speccy#141]
## Detailed description
The `speccy resolve` command returns the following error, which I suspect are caused by the spaces in my (Windows) paths.

```
GET c:/My%20API/some-file.yaml
{ [Error: ENOENT: no such file or directory, open 'c:\My%20API\some-file.yaml']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:    'c:\\My%20API\\some-file.yaml' }
```

As you can see, it seems to be replacing the spaces with `%20`, which I suspect is the cause of the error.

This error only occurs with Speccy v0.8.0.  It works fine with v0.7.3.

## Your environment
Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Node Version:  v10.8.0
* Operating system and version:  Windows 10

**Comment by philsturgeon** [comment]
Reproduced on OS X.

```
▶ node speccy resolve /Users/philsturgeon/src/speccy/test/samples/refs/openapi.yaml
GET /Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml
{ [Error: ENOENT: no such file or directory, open '/Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml' }
{ [Error: ENOENT: no such file or directory, open '/Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml' }
ENOENT: no such file or directory, open '/Users/philsturgeon/src/speccy/test/samples/refs/a%20space.yaml'
```

@MikeRalphson after digging about this seems a lot like something happening in oas-kit.

**Comment by MikeRalphson** [comment]
What does the raw `$ref` value look like in your input document?

**Comment by BigstickCarpet** [comment]
@MikeRalphson - That's right.  The directory path that they're in contains spaces.  For example:

```
cd "C:\path with spaces"
speccy resolve openapi.yaml
```

**Comment by BigstickCarpet** [comment]
Not sure if this is helpful or not, but I had to solve this same problem (illegal URL characters in filesystem paths) in [`json-schema-ref-parser`](https://github.com/BigstickCarpet/json-schema-ref-parser).  Here's the relevant code for converting between filesystem paths and URLs....

https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/util/url.js#L132-L217

**Comment by MikeRalphson** [comment]
@BigstickCarpet Thanks again. I'll try and reproduce on Linux, but if I can't I'll have to put a shout out as `help wanted`. Haven't booted into Windows in 8 months and don't want to break my streak (read: lack the time).

**Comment by BigstickCarpet** [comment]
hahaha.   Totally understand.  I should have clarified... even though I _first_ encountered this bug on Windows, I was _also_ able to reproduce it on Linux

**Comment by philsturgeon** [comment]
@MikeRalphson were you able to reproduce this in Linux?

**Comment by philsturgeon** [comment]
Can confirm! Sadly this missed v0.8.3, but I'll release v0.8.4 when this is approved. https://github.com/wework/speccy/pull/181

**Comment by Gerben-T** [comment]
How come this issue still happens on my Windows machine using the `speccy lint` command (v0.11.0) if it should've been fixed on v0.8.4?

Have you guys tested this on a Windows machine?
I read that this issue doesn't happen anymore on Linux.

**Comment by philsturgeon** [comment]
Probably just use https://github.com/stoplightio/spectral

**Comment by Gerben-T** [comment]
@philsturgeon That works fine for linting thanks, but i just noticed that `speccy resolve` also has the same bug as `speccy lint` and sadly `spectral` has no `resolve` function afaik.

For now i'll be running an old version of Speccy `^0.7.3` where this bug is not present.

Is it worth the time to create a new issue for this?

**Comment by philsturgeon** [comment]
@Gerben-T yeah if you could give us some specifics over here, there were two different bugs discussed in this issue so it's hard to tell whats what. Couldn't recreate in the test suite but if we have some examples it's easier. https://github.com/stoplightio/spectral/issues
