### ISSUE TITLE
Lint rule suggestion: unused components

### ISSUE THREAD

**Issue by jblazek** [wework/speccy#144]
I would like to be able to validate everything in `components` is actually referenced somewhere and fail linting when an unused schema, example, or other element in that section is found.

We have cases where things might get moved around in a spec and it might not be clear something is no longer used.

**Comment by philsturgeon** [comment]
No new rules are being added to speccy, instead that work is being done in https://github.com/Mermade/oas-kit/

Great suggestion though. I'd like this myself. 

In the mean time, I believe tthis tool can help: https://github.com/dolmen-go/openapi-preprocessor
