### ISSUE TITLE
Request for an official Docker image

### ISSUE THREAD

**Issue by bwjohnson-ss** [wework/speccy#155]
It would be great if you could provide an official docker image (published on DockerHub) with speccy installed from NPM so that it could easily be referenced by different CI tools natively.

I found [this](https://hub.docker.com/r/mamis/speccy/), but it lacked any credibility and doesn't include the Dockerfile source.

It would be something as simple as this added to this repo:

```
FROM node:latest
RUN npm install --global speccy
```

**Comment by scottmdahl** [comment]
I created a PR to get the conversation started:

https://github.com/wework/speccy/pull/156

**Comment by bwjohnson-ss** [comment]
@philsturgeon, thanks for merging that. Do you think you'd want to publish official images to [Docker Hub](https://hub.docker.com/)?

**Comment by philsturgeon** [comment]
Fixed in #169
