### ISSUE TITLE
Skip is ignored

### ISSUE THREAD

**Issue by bburtin** [wework/speccy#163]
## Detailed description

I believe that speccy is ignoring `speccy.yaml` and the `--config` option.  I can skip warnings with `--skip`, but not by putting them in **speccy.yaml**.

```
$ node_modules/.bin/speccy --config ./speccy.yaml lint v2api.yaml |& grep -c parameter-description
204
$ node_modules/.bin/speccy --skip parameter-description lint v2api.yaml |& grep -c parameter-description
0
$ cat speccy.yaml
lint:
  skip:
  - parameter-description
```

## Your environment

* Node Version: 10.10
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Ubuntu 18.04

**Comment by erunion** [comment]
I spent some time debugging this last night, and nconf doesn't seem to load the config file at all.

**Comment by TrampGuy** [comment]
Actually `speccy.yaml` seems to work for the `serve` command but not for `lint` - kind of weird.

**Comment by philsturgeon** [comment]
Hey, yep the speccy.yaml is not being ignored, that's why I changed the title of this issue. 

https://github.com/wework/speccy/issues/200 shows the problem, and is asking @MikeRalphson for help on the solution, as we need to be able to either pass skips into the linter, or rewrite some other logic.

**Comment by TrampGuy** [comment]
@philsturgeon Thanks for the quick reply, what I meant was that it's not only the `skip` that doesn't work - passing `rules` through the config file doesn't work for me either.

**Comment by philsturgeon** [comment]
This has been solved thanks to a series of big changes to various parts. @MikeRalphson added skip logic to oas-kit, @pderaaij switched to using it in #248, and I rode some bikes or something. 👍 

If you could test this out I'd appreciate it. If it does not work, please reopen the issue with as much recreatable stuff as possible.
