### ISSUE TITLE
Help wanted: Enhancement: port new linter rule to Speccy

### ISSUE THREAD

**Issue by MikeRalphson** [wework/speccy#200]
## Detailed description

`oas-kit` has a new linter rule definition and example rule as suggested on the APIs you won't hate Slack.

It provides simple `if`/`then` functionality for dependent properties.

See https://github.com/Mermade/oas-kit/commit/ef89a29aa12dab6ba4352fe55c3b87e5f4397470

## Context

At the moment Speccy leverages a lot of `oas-kit` directly, but uses a ported version of the linter code. Suggestions on how to bring these closer together would be welcomed.

## Possible implementation

Should be relatively simple copy and paste, but would require a new test and docs update.

**Comment by MikeRalphson** [comment]
I've raised a PR on `better-ajv-errors` to add handling for `~0` and '~1` escapes, which is basically a must have for reporting errors / warnings under `paths`. https://github.com/atlassian/better-ajv-errors/pull/33

**Comment by philsturgeon** [comment]
#248 should take care of this, and then we won’t need to maintain two sets of rules anymore :)
