### ISSUE TITLE
Serve is displaying x.slice is not a function.

### ISSUE THREAD

**Issue by uxweb** [wework/speccy#207]
## Detailed description

I have a valid OAS3 spec file linted with `speccy lint` but when I want to serve it with `speccy serve` I only can see this error detail:

![image](https://user-images.githubusercontent.com/5134732/48663750-475c7d00-ea5a-11e8-8461-330cba547bff.jpeg)

I'm not sure if this is a bug from ReDoc or Speccy

## Context

I have attached my api spec file so that you can reproduce it in another environment.

[api-description.yaml.txt](https://github.com/wework/speccy/files/2592065/api-description.yaml.txt)

[package.json.txt](https://github.com/wework/speccy/files/2592064/package.json.txt)

## Your environment

* Node Version: v8.12.0
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Mac OS 10.14.1 (18B75)
* Speccy version: 0.8.4 without peer dependencies installed

**Comment by uxweb** [comment]
I found that the examples element in request bodies are not supported yet by ReDoc.

```yaml
components:

  requestBodies:

    AuthBody:
      description: Authentication credentials for a user.
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/AuthCredentials'
          # IF THE NEXT LINES ARE COMMENTED, EVERYTHING IS GOOD!
          examples:
            authCredentialsValid:
              $ref: '#/components/examples/AuthCredentialsValid'
            authCredentialsInvalid:
              $ref: '#/components/examples/AuthCredentialsInvalid'

  examples:
    
    AuthCredentialsValid:
      summary: Valid auth credentials example
      value:
        username: uziel.bueno@naobatec.com
        password: longsecurepassword
    AuthCredentialsInvalid:
      summary: Invalid auth credentials example
      value:
        username: ''
        password: ''
```

**Comment by philsturgeon** [comment]
Looks like you discovered the source of the trouble! Please open an issue on ReDoc if there is not one already.
