### ISSUE TITLE
Feature: Allow pattern matching for object keys via a custom rule

### ISSUE THREAD

**Issue by TrampGuy** [wework/speccy#214]
## Detailed description

Currently there doesn't seem to be a way to match a pattern against an object's keys via the pattern custom rule, or any other way.
The only rule which allows key validation through a custom rule is `notEndWith` and the usage is documented in only in the code.

## Context

I would like, for example, to check all the `paths` keys and see that they match a specific pattern - alphanumeric with no underscore and special chars (for example).
I would also like to match all the `properties` keys and see that they are all camel case.

Matching a pattern against the keys is a powerful validation tool that would surely bump speccy's functionality for all users.

## Possible implementation

A naive approach would be to try and utilize the work already done for the `notContain` rule. Using `$key` to set a `propertyValue` could be shared with all rules really, and a similar logic could be implemented in the `pattern` rule, and maybe others as well.

**Comment by bottoy** [comment]
I had the same use case - to check if a Paths object in a swagger contains a resource for his health.
I adapted the code and created pull request #232

Unclear for me why the automated check fails ...

**Comment by philsturgeon** [comment]
Job done in #239

**Comment by pburls** [comment]
@philsturgeon any idea when the next release will be? Looking forward to using this feature asap.
