### ISSUE TITLE
Feature: Add simple array validation rules

### ISSUE THREAD

**Issue by TrampGuy** [wework/speccy#215]
## Detailed description

Most current rules don't seem to support a property (object) containing an array.

## Context

Given the following:
```
security:
  - A
    - aaa
  - B
    - bbb
```
I would like to check if the `security` property contains at least one of `A, B or C`

I thought `or` might do it, but it turns out most of the rules don't quite support this array structure.

**Comment by TrampGuy** [comment]
Is this not described properly? too wide? or could already be achieved somehow?

**Comment by pderaaij** [comment]
Not completely sure, but when #239 is merged you can try with using `$key` as a parameter and make a regex for it. Not the most beautiful way but it might work.

I created the following rule to make sure an oauth2 security scheme is defined:

>       {
>            "name":"security-scheme-oauth2",
>            "object": "securityScheme",
>            "enabled": true,
>            "description": "must define an oauth2 security scheme",
>            "pattern": { "property": "type", "value": "oauth2" }
>        }

**Comment by MikeRalphson** [comment]
You might want to anchor that regex value, just in case.

**Comment by philsturgeon** [comment]
It's been merged, so you can pull and try with master, or use `docker run wework/speccy:nightly lint foo.yaml`.

**Comment by MikeRalphson** [comment]
The next version of the `oas-kit` linter has a JSON `schema` rule, so I think you could do something like:

```yaml
name: oneof-a-b-or-c
object: security
schema:
  type: array
  items:
    oneOf:
    - required:
      - A
    - required:
      - B
    - required:
      - C
```

**Comment by philsturgeon** [comment]
Great work Mike! All new rules will be going in via oas-kit, and once we merge #248 we'll have all their awesome rules.
