### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by floggle** [wework/speccy#219]
There don't seem to be any docs on installation. You seem to be pre-supposing that all users know about node.js.

Also, after googling around and figuring out how I think it should work, it still doesn't work:

```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/markedjs/marked.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
```
I shouldn't need GIT to be installed for this. Especially given I've manually installed markedjs manually now - it's still looking for git.

**Comment by philsturgeon** [comment]
Hey @floggle! Well, unfortunately seeing as this is a node module, you'll need to know how to install a node module. A dependency of a dependency is being pulled in over Git for some reason, that's not really something I can do anything about. 

But, if you'd like to use Docker instead, that is an option which is described in the README.

```
$ docker run wework/speccy lint https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml
```

This avoids needing to have NPM or Yarn installed locally, or even NodeJS at all.  It does of course you need docker locally, so its up to you which you'd rather use. 👍
