### ISSUE TITLE
how to use --config option with lint ?

### ISSUE THREAD

**Issue by toschder** [wework/speccy#220]
I´m trying to figure out how --config option is working.
I expected speccy lint --config ./myspeccy.myExtension petstore.yaml - but nothing happens.

## Detailed description
- I´ve added a ./speccy.yaml with non-existing lint:rules folder - the file seems to be ignored
- I´ve passed a --config /path/to/config.yaml option - nothing happened, options is totally ignored.

## Context
I would like to add some "custom rules" in the speccy.yaml, together with some other general options.

## Possible implementation
If --config option needs to be passed in another way or style, there should be an error message. maybe -h can have some examples, or at least the README?

## Your environment
Ubuntu, running speccy 0.8.5

* Node Version:
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by philsturgeon** [comment]
Config file in general works fine, but #163 highlights and issue with skips and rules, and https://github.com/wework/speccy/pull/204 is where we are tracking the solution.

**Comment by philsturgeon** [comment]
This has been fixed and is released in dev version v0.9.0-1:

```
npx speccy@0.9.0-1 lint foo.yaml
```

Please confirm if its working for you. If not, we need more tests :D
