### ISSUE TITLE
speccy - h command [options] or [options] command ?

### ISSUE THREAD

**Issue by toschder** [wework/speccy#221]
The speccy lint -h output implies that options are supposed to come before the filename:

$ node_modules/.bin/speccy lint -h
Usage: lint [options] <file-or-url>

At http://speccy.io/rules/1-rulesets#set-default it´s stated the other way round:
$ speccy lint openapi.yaml --rules=default

## Detailed description

Please try to get the right configuration options as clear as possible, especially when combining with the general --config option (that looks like it is not working)

## Context

it´s important to get short-hand samples, running out-of-the box for common use cases.
(like using the --config option)

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Ubuntu, speccy 0.8.5

**Comment by philsturgeon** [comment]
Fixed in v0.8.6.
