### ISSUE TITLE
Component responses resolving external files in an odd fashion

### ISSUE THREAD

**Issue by catharsisjelly** [wework/speccy#23]
## Description

When referencing external files within components it seems as though the reference requires a director e.g. `./`. In the example repo if you remove the `./` on https://github.com/catharsisjelly/speccy-test/blob/316c892b70c6c9d50d5d99aca07c8232f74be3d3/api.yml#L87 then the linting does not pass. However note that the reference https://github.com/catharsisjelly/speccy-test/blob/316c892b70c6c9d50d5d99aca07c8232f74be3d3/api.yml#L70 does not need this `./`.

I think this is related somehow to the original problem I had where external references did not seem to be finding other external references. There is an example of this included in the repo, just uncomment line 30.

## Context

This will allow people building API's to split their resources into smaller and more manageable chunks

## Your environment

Linux Mint running Node 8.10.0 lts

Example in the following repo

https://github.com/catharsisjelly/speccy-test

**Comment by catharsisjelly** [comment]
I will happily put all three files in the gist in the initial issue if you prefer

**Comment by MikeRalphson** [comment]
When I rename `responses.yml` to `responses.yaml` (as per the `$ref`s) this example resolves ok for me, and lints ok in speccy.

Perhaps it would be a good idea for speccy to implement the `--verbose` option though,

**Comment by catharsisjelly** [comment]
@MikeRalphson I tried this today after you pointed out my error but I still get the same error. Is there any more information I can provide to see what's happening?

**Comment by MikeRalphson** [comment]
@catharsisjelly probably not until we get the `--verbose` option working and cut a new release.

**Comment by catharsisjelly** [comment]
I had a thought that because I have speccy installed globally that I may not have been using node 8.10. I checked and it turned out my default was node v9.6.1. I used nvm to install 8.10, make it defa\ult and reinstall speccy. This has given me a different error for the same example. I'll update the initial issue with this too.

```
~/Documents/openAPITest » whereis speccy
speccy: /home/chris/.nvm/versions/node/v8.10.0/bin/speccy

~/Documents/openAPITest » speccy lint main.yml
Specification contains lint errors: 2

#/paths/~1administrators~1{userId}/put/responses/200/content/application~1json/schema  R: reference-components-regex  D: reference components should all match spec. regex
reference components should all match spec. regex

#/paths/~1administrators~1{userId}/put/responses/200/content/application~1json/schema  R: reference-components-regex  D: reference components should all match spec. regex
reference components should all match spec. regex
```

**Comment by philsturgeon** [comment]
This looks like speccy is working just fine for 8.10. I've added 9 coverage to circleci. https://circleci.com/workflow-run/379bde64-ecbf-4aab-8338-dabad69a861e

**Comment by catharsisjelly** [comment]
Sorry @philsturgeon I don't understand. To me those references look fine are you able to explain why is speccy (v0.5.0) highlighting them as an error?

**Comment by philsturgeon** [comment]
Look at the rule definition, the reflex wants external refs to start with ./

Is that the trouble? I e got an issue to make regex mismatch errors better. Right now they’re clear as mud. 

—
Phil Sturgeon

**Comment by catharsisjelly** [comment]
@philsturgeon thanks for the suggestion. I've had another play and made a small test repo (and will update the main issue) but the issue seems to appear as soon as I reference an external file within the components.

**Comment by philsturgeon** [comment]
Trying to recreate your issue here, but it seems fine https://github.com/wework/speccy/pull/28

**Comment by philsturgeon** [comment]
Here is the verbosity fix @MikeRalphson requested: https://github.com/wework/speccy/pull/29

**Comment by catharsisjelly** [comment]
Thanks for the continued work and support on this. I tried tonight to run the spec through a debugger (using `node --inspect`) using my test repo I put in a breakpoint [here](https://github.com/wework/speccy/blob/c2b18ce8d136f39e5a694d5efa2eb516f13151b2/lib/linter.js#L141) and then ran through it a few times. I found it odd that the reference in the components is never processed but I might be totally barking up the wrong tree (just trying to help where I can).

I also checked my test repo using version `0.4.1` which passes with or without the `./`in the components

**Comment by philsturgeon** [comment]
@catharsisjelly how is it going now? A good way to test things is to clone the repo, run `npm install`, then use `node speccy lint /path/to/foo.yml` so you can test against actual master instead of specific versions. If its working in master we're all good. Also 👋 to a fellow Bristolian.

**Comment by catharsisjelly** [comment]
I'll take a look asap, thanks @philsturgeon :smiley:

**Comment by catharsisjelly** [comment]
@philsturgeon awesome work, thank you for continuing to look into this and fix it :)
