### ISSUE TITLE
Question: proper flow with resolve and lint

### ISSUE THREAD

**Issue by dlouzan** [wework/speccy#235]
I'd like to know which flow do you guys use for resolve + lint.

My use case is I'd like to follow @philsturgeon suggestion in his blog and set an api-first workflow for our team, writing OpenAPI 3 with JSON Schema data models.

As part of this, I'd like to configure my CI to validate all schemas, and lint all OAS files.

Currently I have something like this:

```bash
# Verify JSON Schemas
$ ajv compile -s "schemas/*.json" -r "schemas/*.json" --verbose

# Convert JSON Schema models to OpenAPI-flavor and lint
$ speccy lint <(speccy resolve openapi.yaml -j)
```

The issue with this flow is that it seems speccy cannot work with stdin, so I either have to work with temporary files, or do [process substitution in bash](http://tldp.org/LDP/abs/html/process-sub.html) as above, but process substitution has known issues with error handling.

Am I missing anything? how do you guys do this?

What I'm thinking right now is providing a PR that enables stdin support for speccy, so that I can properly pipe the commands and have proper error handling, and maybe add some extra info in the readme:

```bash
$ speccy resolve openapi.yaml -j | speccy lint
```

**Comment by philsturgeon** [comment]
That PR would be fantastic, thank you. It's come up in conversation once or twice around the place, but it's not been worked on before.
