### ISSUE TITLE
CircleCI builds broken

### ISSUE THREAD

**Issue by pderaaij** [wework/speccy#241]
Currently the builds in CircleCI are broken. 

Unsure who is owning the project in CircleCI, but would be great if the following things could be checked.

- Environment variable `COVERALLS_REPO_TOKEN` configured in the CircleCI project
- If set, refresh the token via https://coveralls.io/refresh?private=true

Would be nice if the builds are working properly again.

Thanks in advance!

**Comment by pderaaij** [comment]
It is a bit weird that the builds triggered by `dependabot` are working properly.

**Comment by philsturgeon** [comment]
When I added docker pushing I had to disable env variables for forked repos, and I'm still trying to figure out how to enable coveralls without leaking secrets.

**Comment by pderaaij** [comment]
Tricky one, did some research but didn't found that much useful. Will have another look when I have more time.
