### ISSUE TITLE
New rule action for object keys

### ISSUE THREAD

**Issue by pderaaij** [wework/speccy#242]
## Detailed description

For my custom rule set that I am creating I would love to have a rule that checks the keys of an object according to a pattern. For example, having a custom rule that ensures the property names are in snake_case. 

This is especially tricky in the `schema` object as fields in the schema object are a schema object on its own. I've played around with several options within the current abilities but came short every time. 

## Possible implementation

I would like to introduce a new rule action that targets the keys of an object, applying a pattern to each and every key. 

In my local environment I have this as a rule definition

>      {
>            "name":"schema-property-name-snake-case",
>            "object": "schema",
>            "enabled": true,
>            "description": "parameter must be in snake_case",
>            "keyPattern": { "property": "properties", "value": "^([a-z_])*$" }
>        }

and introduced the following to the linter

```javascript
             if (rule.keyPattern) {
                const { property, value } = rule.patternForKey;
                const target = (property) ? object[property] : false;

                if (target) {
                    const re = new RegExp(value);
                    const keys = Object.keys(target).forEach(key => {
                        options.context.push((options.context[options.context.length - 1] + '/' + key).split('//').join('/'));
                        ensure(rule, () => {
                            should(re.test(key)).be.exactly(true, rule.description);
                        });
                        options.context.pop();
                    });
                }
            }
```

I am curious if this is something we would like to add or is a bad approach.

**Comment by philsturgeon** [comment]
I'd take this up with @MikeRalphson over on the https://github.com/Mermade/oas-kit/ project, as I'm trying to move over to using their linter, instead of continuing to maintain the copy/tweaked version of their code.

**Comment by philsturgeon** [comment]
Currently we're tracking that in #204 but I dropped the ball on doing the actual work.

Basically, the oas-linter needs to be tweaked a little, and our code needs to change in order to wrap it a little, so that we can just delete the linter. I was attempting this by copying and pasting the linter/index.js to see what the diff was, then trying to update stuff accordingly. 

If you can do that and interface with Mike that would be amazeballs.

**Comment by MikeRalphson** [comment]
@philsturgeon do you have the GitHub beta of 'move issue' turned on? If so, feel free to punt this issue over to `oas-kit`.

**Comment by pderaaij** [comment]
I will have a look at in the weekend.

**Comment by philsturgeon** [comment]
@MikeRalphson i think I need some perms on oas-kit to do that.

**Comment by MikeRalphson** [comment]
@philsturgeon collaborator invite sent.

**Comment by philsturgeon** [comment]
@MikeRalphson looks like you'll have to copy and paste it :D

**Comment by MikeRalphson** [comment]
@pderaaij could you open a new issue on `oas-kit`? Just copying and pasting the initial description with a link to this issue will be fine. I have some bookmarks which ignore issues I've opened myself so it would be good if the issue was properly attributed.

**Comment by pderaaij** [comment]
Done: https://github.com/Mermade/oas-kit/issues/128

Happy to help if required!
