### ISSUE TITLE
x-miro is added in the resolved spec even after explicitly setting preserveMiro: false

### ISSUE THREAD

**Issue by Shwetap05** [wework/speccy#268]
Using latest npm package of speccy and even after setting preserveMiro: false in options, seeing it added in resolved spec, when loading this spec in swagger editor its complaining about it.

**Comment by pderaaij** [comment]
In what file do you set the options?

**Comment by Shwetap05** [comment]
Calling speccy from typescript code like below and passing the option there.

private static options = {
        resolve: true,   // Resolve external references
        jsonSchema: true, // Treat $ref like JSON Schema and convert to OpenAPI Schema Objects
        preserveMiro: false // Flag to resolver as to whether to preserve old value of $ref in x-miro
      };

    static async ResolveReferences(documentUrl: string)
    {
        return new Promise<string>(async (resolve,reject) => {
            loader.loadSpec(documentUrl,SpeccyClient.options,(err,data ) => {
                if (err) {reject(err);}
                else {resolve(JSON.stringify(data));}
            })
        })
    }

**Comment by NathanAtKadaster** [comment]
I'm having this issue using the docker image as well. I don't think the x-miro extensions should be in a resolved spec at all. Default behaviour should be `preserveMiro: false`. I thought this was fixed as per #187 and #198, but it looks like this behaviour is still there in 0.9.0.

I was using Docker image `wework/speccy:0.9.0` and still get invalid specs after resolving.

**Comment by dlouzan** [comment]
I'm also experiencing this, plus the generated code goes against one of the lint rules:\
https://speccy.io/rules/1-rulesets#reference-no-other-properties

**Comment by MikeRalphson** [comment]
Anyone with a nice short input definition as a repro case?

**Comment by dlouzan** [comment]
I have just added a new issue in oas-kit for this

**Comment by timonbimon** [comment]
also having the same issue :(

**Comment by djtarazona** [comment]
Fixed here https://github.com/Mermade/oas-kit/issues/152#issuecomment-465963165
