### ISSUE TITLE
ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by stereobooster** [wework/speccy#273]
## Detailed description

I run `speccy` and get confusing error. I'm pretty sure there is an error in my OAS3 schema, but error message is not helpful

```
npx speccy lint oas3.json
ENOENT: no such file or directory, open 'projects/oas3/TypedLiteral'
```

## Context

I expect helpful error

## Your environment

* Node Version:v10.15.0
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Mac OS X
* Link to your project: project is closed source, but I will try to isolate issue and create reproducible demo

**Comment by stereobooster** [comment]
The problem is that my schema contains

```json
{
  "$ref": "TypedLiteral"
},
```

but instead it should be

```json
{
  "$ref": "#TypedLiteral"
},
```

Helpful error would be: "Found external $ref at file:line, but corresponding file is missing. You need either provide file or mark reference as internal by prefixing with #"

**Comment by pderaaij** [comment]
Feels this should be solved in `oas-validator` as that projects tries to resolve the references. I'll have a look later this week.
