### ISSUE TITLE
Default lint rule "path-keys-no-trailing-slash" does not match keys under paths

### ISSUE THREAD

**Issue by jdemelo** [wework/speccy#285]
## Detailed description

BUG: The default rule `path-keys-no-trailing-slash` is not applied.

## Context

**Expected behavior**:
- paths with trailing slashes should fail on the rule `path-keys-no-trailing-slash`

**Observed behavior**:
- paths with trailing slashes do not fail on the rule `path-keys-no-trailing-slash` 
- if the rule is modified, such that `object: paths` -> `object: "*"`, then it will detect paths with trailing slashes

**Steps to reproduce**:
- modify a yaml spec file so that it has a path key with a trailing slash
- run `speccy lint -v specfile.yaml` and see that validation does not fail on the rule `path-keys-no-trailing-slash`

**Why is this change important to you/others? How would you use it?**
- It would be nice to validate paths

## Possible implementation

🤷‍♂️

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Node Version: v11.8.0
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 10.14.1

**Comment by djtarazona** [comment]
This has been fixed in [v0.11.0](https://github.com/wework/speccy/releases/tag/v0.11.0)
