### ISSUE TITLE
ENOENT: no such file or directory error caused by circular reference path issue

### ISSUE THREAD

**Issue by heitortsergent** [wework/speccy#288]
I ran into this weird error when trying to separate the usual `petstore.yaml` spec example into two separate files. When running the `lint` command, I would get the message:

`ENOENT: no such file or directory, open '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml'`

## Detailed description

Running the `lint` command again with the -v option outputs:

```
GET petstore.yaml
GET /Users/heitor/app dev/openapi3-ref-example/endpoints/pet.yaml #/paths/~1pets
CACHED /Users/heitor/app dev/openapi3-ref-example/endpoints/pet.yaml #/paths/~1pets~1{petId}
GET /Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml #/components/schemas/Pets
{ Error: ENOENT: no such file or directory, open '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml' }
{ Error: ENOENT: no such file or directory, open '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml' }
ENOENT: no such file or directory, open '/Users/heitor/app%20dev/openapi3-ref-example/petstore.yaml'
```

My specification consisted of 2 files: 

- `petstore.yaml`, which contained a paths object that referenced the second file for the details of each endpoint, and the components object with the schemas for the API
- `pet.yaml`, which contained the full paths object with all the endpoints, and referenced the schemas from the `petstore.yaml` file

I'm not sure if this is the issue, but it seems that when trying to resolve the back and forth references between the two files, something changes the path and breaks the linting process. You can see before the first error line of the verbose output, the `/app dev` changes to `/app%20dev`.

I moved the project to another folder where the path didn't contain any space characters, and the lint command works just fine. 🤷‍♂️ 

## Your environment

* Node Version: 9.11.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOs Mojave 10.14.2
* Link to your project: https://github.com/heitortsergent/openapi3-ref-example

**Comment by HeyRatFans** [comment]
We're having a similar problem at work. 

I've tracked the issue down to a problem with oas-resolver and how it uses [URL](https://nodejs.org/api/url.html) to parse the local filesystem paths. By using URL, the path is URL-encoded which results in the spaces being converted  to %20 which then results in the file not being found.

I have opened a ticket with oas-kit [here](https://github.com/Mermade/oas-kit/issues/162)
