### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pmaderamitlasf1** [wework/speccy#300]
speccy lint yaml_obj.yml --rules=test.rule 
(node:50261) ExperimentalWarning: The http2 module is an experimental API.
Specification contains lint errors: 2
/usr/local/lib/node_modules/speccy/lint.js:58
${colors.yellow + pointer} ${colors.cyan} R: ${rule.name} ${colors.white} D: ${rule.description}
                                                    ^

TypeError: Cannot read property 'name' of undefined
    at lintResults.forEach.result (/usr/local/lib/node_modules/speccy/lint.js:58:53)
    at Array.forEach (<anonymous>)
    at formatLintResults (/usr/local/lib/node_modules/speccy/lint.js:54:17)
    at validator.validate (/usr/local/lib/node_modules/speccy/lint.js:98:30)
    at /usr/local/lib/node_modules/speccy/node_modules/call-me-maybe/index.js:13:28
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by MikeRalphson** [comment]
Can you add the contents of your `rule.yaml` file, it looks like one or more rules are missing a `name` property.

**Comment by pmaderamitlasf1** [comment]
I used the default rule file:

rules:
- name: parameter-description
  object: parameter
  description: parameter objects should have a description
  truthy: description
- name: parameter-name-regex
  object: parameter
  disabled: true
  description: parameter names should match RFC6570
  pattern:
    property: name
    value: ''
- name: operation-operationId
  object: operation
  description: operation should have an operationId
  truthy: operationId
- name: operation-summary-or-description
  object: operation
  description: operation should have summary or description
  or:
  - summary
  - description
- name: operation-tags
  object: operation
  description: operation should have non-empty tags array
  truthy: tags
  skip: isCallback
- name: path-keys-no-trailing-slash
  object: paths
  description: paths should not end with a slash
  notEndWith:
    property: "$key"
    value: "/"
- name: server-trailing-slash
  object: server
  description: server url should not have a trailing slash
  notEndWith:
    property: url
    value: "/"
- name: openapi-tags
  object: openapi
  description: openapi object should have non-empty tags array
  truthy: tags
- name: openapi-tags-alphabetical
  object: openapi
  description: openapi object should have alphabetical tags
  alphabetical:
    properties: tags
    keyedBy: name
- name: reference-no-other-properties
  object: reference
  description: reference objects should only have a $ref property
  truthy: "$ref"
  properties: 1
- name: example-value-or-externalValue
  object: example
  description: example should have either value or externalValue
  xor:
  - value
  - externalValue
- name: default-and-example-are-redundant
  object: "*"
  description: don't need to define an example if its exactly the same as your default
  schema:
    dependencies:
      default:
        properties:
          example:
            not:
              const:
                "$data": "1/default"
- name: reference-components-regex
  object: reference
  disabled: true
  description: reference components should all match regex ^[a-zA-Z0-9\.\-_]+
  pattern:
    property: "$ref"
    omit: "#"
    split: "/"
    value: "^[a-zA-Z0-9\\.\\-_]+$"
- name: no-script-tags-in-markdown
  object: "*"
  description: markdown descriptions should not contain <script> tags
  notContain:
    properties:
    - description
    value: "<script"
- name: info-contact
  object: info
  description: info object should contain contact object
  truthy: contact
- name: license-apimatic-bug
  object: license
  description: license url should not point at gruntjs
  notContain:
    properties:
    - url
    value: gruntjs
- name: no-eval-in-descriptions
  object: "*"
  description: markdown descriptions should not contain 'eval('
  notContain:
    properties:
    - description
    - title
    value: eval(

**Comment by pmaderamitlasf1** [comment]
@MikeRalphson  Here is more info on this issues:

Looks like the results has some non object results like:

Specification contains lint errors: 4
Test string [ 'Anonymous requestBody: requestBody_definition',
  'Anonymous requestBody: requestBody_message',
  { pointer: '#/info',
    rule: 
     { name: 'info-contact',
       object: [Array],
       description: 'info object should contain contact object',
       truthy: [Array],
       url: undefined },
    ruleName: 'info-contact',
    error: 
     { AssertionError: expected Object {


this is causing the error , so on adding a if condition in formatLintResults function as below may fix the issue .


const formatLintResults = lintResults => {
    console.log("Test string", lintResults)
    let output = '';
    lintResults.forEach(result => {
        console.log("Test  results", result);
        if (result.rule){
            const { rule, error, pointer } = result;

            output += `
        ${colors.yellow + pointer} ${colors.cyan} R: ${rule.name} ${colors.white} D: ${rule.description}
        ${colors.reset + truncateLongMessages(error.message)}
    
        More information: https://speccy.io/rules/1-rulesets#${rule.name}
        `;

        }

    });

    return output;
}

**Comment by pderaaij** [comment]
This will be solved with my current PRs and in a next release of speccy. Please have a look at it when released.

**Comment by djtarazona** [comment]
This has been fixed in [v0.11.0](https://github.com/wework/speccy/releases/tag/v0.11.0)
