### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by brokenmass** [wework/speccy#319]
## Detailed description

Speccy npm version has not been updated since early January.

## Context

The latest improvements available on the git repo (piping for example) are not available on the latest released version on npm `0.9.0`

## Possible implementation

Trigger an NPM release

**Comment by brokenmass** [comment]
@djtarazona : any update ?

also, can you please allow piping to the `serve` command too ?

**Comment by brokenmass** [comment]
@djtarazona any update ?

**Comment by djtarazona** [comment]
I'll be cutting a release this week. Sorry for the delay!

**Comment by pderaaij** [comment]
@djtarazona I'll see if I can fix some of my PRs today or tomorrow so that they can be taken along.

**Comment by djtarazona** [comment]
Sounds good. If they don't make it, we can do a quick subsequent minor release.

**Comment by djtarazona** [comment]
[v0.10.1](https://github.com/wework/speccy/releases/tag/v0.10.1) has been released 🙂
