### ISSUE TITLE
Doc site https://speccy.io/ is not secure

### ISSUE THREAD

**Issue by exoego** [wework/speccy#321]
## Detailed description

`doccy` shows a message like this `More information: https://speccy.io/rules/~~` when found issues.

When I opened such link, e.g. https://speccy.io/rules/1-rulesets#info-contact, browsers raise warnings saying "Your connection is not secure"
![image](https://user-images.githubusercontent.com/127635/56769470-40495000-67ec-11e9-9a42-7d7b038b5763.png)

## Context

Insecure docs site may discredit Speccy.

## Possible implementation

* Option1 (preferrable): Configure SSL cerficiation properly. https is everywhere nowadays.
* Option2:  Change schema of hyperlinks in message to `http://`

## Your environment

* Speccy: 0.9.0
* Node Version: 10.15.3
* Operating system and version: Ubuntu 18.04

**Comment by pderaaij** [comment]
@djtarazona ^^

**Comment by djtarazona** [comment]
Thanks, looking into this.

**Comment by djtarazona** [comment]
This should be fixed now 👍
