### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by philsturgeon** [wework/speccy#345]
speccy.io doesn’t work anymore. I transferred domain ownership over to Pascal but the DNS isn’t doing anything. It’s github pages so should be a quick fix.

**Comment by djtarazona** [comment]
Are you sure? I was just working on this yesterday to fix an HTTPS issue. It's up for me. Can you double check? I'll dig into it more if you are still experiencing an issue.

**Comment by philsturgeon** [comment]
Awesome! It was down for a few weeks I think, I got a few emails and kept forgetting to write up an issue about it. I guess you fixed it some time between my last email and today. :D Hope all is well 👋
