### ISSUE TITLE
[Enhancement] Lint errors should show line numbers

### ISSUE THREAD

**Issue by elyobo** [wework/speccy#346]
## Detailed description

Line numbers should be shown (where possible; if the spec is a single line JSON string then there's not much to be done) in linting errors.

## Context

Jumping to the error line would make fixing up errors much easier.

## Possible implementation

N/A

## Your environment

N/A

**Comment by pderaaij** [comment]
This should be fixed in #338, @djtarazona can you have a look at the open PRs?

**Comment by djtarazona** [comment]
This has been added in [v0.11.0](https://github.com/wework/speccy/releases/tag/v0.11.0)

**Comment by elyobo** [comment]
Excellent, thanks!

Anyone care to check out my other PR? ;)

**Comment by djtarazona** [comment]
@elyobo Yes, it is a larger PR so I didn't have time to review it this weekend but it's on my list. In the meantime, it has some conflicts if you don't mind resolving those?

**Comment by elyobo** [comment]
Thanks, I'll be able to look in to the conflicts this evening AU time.
