### ISSUE TITLE
Allow Resolve to merge unrelated spec files.

### ISSUE THREAD

**Issue by davinchia** [wework/speccy#382]
## Detailed description
I'm wondering if its possible to use speccy to combine un-related spec files.

## Context
I'm exploring different ways to serve OpenApi documentation. Redoc is the top choice. However serving multiple spec files is unwieldy/manual. It'll be great if speccy would also allow the merging of unrelated spec files. e.g. `speccy resolve file1.yaml file2.yaml file3.yaml -o big-file.yaml`. This would allow one to write disparate spec files and use redoc-cli out of the box. 

## Possible implementation
Haven't taken a look at the code base. Curious if I've missed anything/this is already in the works. If this cannot be done/is not in the works, I'm happy to take directions and contribute.

## Your environment
Mac + Linux. Planning on docker, so not too important.

**Comment by MikeRalphson** [comment]
This is out-of-scope for the resolver/bundler Speccy uses under the hood (oas-kit's oas-resolver). Though this doesn't mean another command can't be added to Speccy, it may be worth looking at other github projects tagged `openapi` and `merge` to see if there's a pre-processor which already meets your needs.

**Comment by davinchia** [comment]
Thanks for the quick reply. I'll take a look around. Closing this in the mean time.
