### ISSUE TITLE
Split linter into a separate package

### ISSUE THREAD

**Issue by pkuczynski** [wework/speccy#396]
Right now `speccy` serves a few different purposes: to lint and to serve api documentation. When one needs to only lint but does not require serving, he is bombarded with lots of missing peer dependencies errors. This is quite annoying.

Do you think it would be possible to extract the linting part to a separate package so it could be used independently?

**Comment by MikeRalphson** [comment]
The validator and linter functionality are already provided by separate packages: `oas-validator` and `oas-linter` which are maintained.

**Comment by pkuczynski** [comment]
I ended up using `spectral` although they have a quite annoying issue at the moment https://github.com/stoplightio/spectral/issues/955

**Comment by MikeRalphson** [comment]
That's not a ~~moon~~ bug.

**Comment by pkuczynski** [comment]
How come it's not?

**Comment by MikeRalphson** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#patterned-fields-1

> This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML

**Comment by pkuczynski** [comment]
In JSON it must be wrapped into "" but not in yaml. Different formats, different requirements. Does not make sense to force json requirements into yaml.

**Comment by pkuczynski** [comment]
Please note, that even swagger editor do not use "" for responses, as I presented in stoplightio/spectral#955

**Comment by MikeRalphson** [comment]
YAML allows numeric keys, so that is exactly the reason they need to be quoted  to force them to be strings (this is only an issue for some languages / libraries, but the goal is interoperability). The bug is in swagger-editor, not Spectral.

**Comment by pkuczynski** [comment]
I raised a PR for OpenAPI spec to clarify this issue https://github.com/OAI/OpenAPI-Specification/pull/2147

**Comment by pkuczynski** [comment]
Which languages/libraries have an issue with parsing yaml keys which are numbers and not strings?

**Comment by MikeRalphson** [comment]
> I raised a PR for OpenAPI spec to clarify this issue OAI/OpenAPI-Specification#2147

I'll let the other members of the OAI TSC weigh in then.

> Which languages/libraries have an issue with parsing yaml keys which are numbers and not strings?

Any language which allows numeric keys in objects/hashes/dictionaries where the yaml parsing library doesn't force keys to be strings. The key `200` and `"200"` would not be equal.

**Comment by pkuczynski** [comment]
They also do not need to be equal, do they?

**Comment by MikeRalphson** [comment]
If you could have both properties, which is tooling supposed to use?

**Comment by pkuczynski** [comment]
Linter should be able to find duplicate keys easily. Spectral is written in js, so `200 == '200'`
