### ISSUE TITLE
How to write rules for parameters?

### ISSUE THREAD

**Issue by erunion** [wework/speccy#4]
There's some existing rulesets in place for `pathItem`, but they don't seem to expand past `summary` and `description` on those paths. How can I go about writing a ruleset for enforcement on a parameter, such as requiring it has summary?

**Comment by MikeRalphson** [comment]
You would simply enforce the rule on the `parameter` object itself. It may only be an example, but `parameter` objects don't have a `summary` property in v3.0.x
