### ISSUE TITLE
Multi $ref ?

### ISSUE THREAD

**Issue by kota65535** [wework/speccy#424]
Multiple $refs inside a single object is the one of the strongly requested features as discussed in here:
https://github.com/OAI/OpenAPI-Specification/issues/417

But maintainers are very reluctant to change its behavior, because OpenAPI uses $ref as JSON Reference as it is defined in JSON schema.
How about supporting this function in this tool?

**Comment by MikeRalphson** [comment]
Very unlikely. Speccy is built on libraries which enforce the OpenAPI schema, and secondly, Speccy is unmaintained.

**Comment by kota65535** [comment]
Got it. I will make some or contribute to another tool.
