### ISSUE TITLE
Combine the options.context log info

### ISSUE THREAD

**Issue by LucasDvp** [wework/speccy#50]
Try to make a user friendly log info, the **options.context Object** should have a strict uniformed structure to show.

**Comment by MikeRalphson** [comment]
It does, it's a JSON Pointer, just like you use in `$ref`s.

**Comment by LucasDvp** [comment]
emmmmm.... so how can I use this, I run `speccy lint -j <path-of-file>` but nothing changed, the code shows `-j` should not need more params, can you give me one example?

**Comment by philsturgeon** [comment]
Hey @LucasDvp, not sure whats happening here. @MikeRalphson was not suggesting you use the `-j` switch, that's for treating $ref's as JSON Schema and converting them on the fly. 

The issue tracker has a suggested template, which asks that you clearly explain the issue, declare if its a bug or a feature request, asks for suggested solutions and a few other things. It's a few ideas suggested on [this awesome article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

It kinda seems like @MikeRalphson has provided some information, so we might be good here. If you have further concerns/questions/suggestions then please make a new issue.
