### ISSUE TITLE
Silently fails to resolve $ref which does not exist

### ISSUE THREAD

**Issue by philsturgeon** [wework/speccy#53]
Noticed that speccy was giving a valid response on a spec which was $ref'ing a non-existent file.

## Detailed description

When linting with the `--verbose` switch, $ref that points to a missing file shows something like this:

```
... everything is fine up here...
Creating initial clone of data at #/paths/~1foos/post/responses/400/content/application~1json/schema/properties/result
Skipping ref from other source /Users/psturgeon/src/rails-template/docs/components/schemas/foo.json
GET /Users/psturgeon/src/rails-template/docs/components/schemas/foo.json
{ Error: ENOENT: no such file or directory, open '/Users/psturgeon/src/rails-template/docs/components/schemas/foo.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/psturgeon/src/rails-template/docs/components/schemas/foo.json' }
Finished resolution!
Specification is valid, with 0 lint errors
```

That needs to fail much harder.

## Your environment

* Node Version: v8.11.1
* Operating system: OSX
* Speccy: master

**Comment by boyanyordanov** [comment]
I haven't done any serious NodeJS development but I think I know enough js to be able to help. 
That said, I'll study the code a bit and give it a shot.

**Comment by philsturgeon** [comment]
@boyanyordanov hey! Thank you for offering to help, but I had some time and needed to get this done. It was effecting things at work. 😅 

https://github.com/wework/speccy/pull/66

**Comment by boyanyordanov** [comment]
I am sorry I couldn't get it done faster. 😅
Error handling in Node is awfully confusing to me. I will study your solution and will keep an eye for smaller issues in future.
