### ISSUE TITLE
"Would You Like To Know More?" Links

### ISSUE THREAD

**Issue by philsturgeon** [wework/speccy#54]
![image](https://user-images.githubusercontent.com/67381/38736856-69072834-3efb-11e8-9d69-a83ed1c76af3.png)

## Detailed description

Right now the errors are not always clear to folks who aren't super into OpenAPI specifications, so we need to provide links to more information.

## Context

Both @rachelsison and @iainmcgin have requested this feature this week. 😅

## Possible implementation

An easy step forward would be linking to the anchor that relates to the object being linted, so if we're saying "openapi" is missing the "tags" object, we can link to `https://swagger.io/specification/#oasObject`, which describes what the tags object should be and offers a link to learn more.  

I'd also like to get a mini site up on speccy.io, which will explain each of the built in suggestions in more detail. _Why_ do you need a tags object? Do I _really_ need to write descriptions for parameters?

**Comment by MikeRalphson** [comment]
Please consider linking to `specs.openapis.org` when its there and not `swagger.io/specification`. Rule links to expanded descriptions and examples are a great idea.
