### ISSUE TITLE
Output multiple validation problems at once

### ISSUE THREAD

**Issue by bobvanderlinden** [wework/speccy#55]
## Detailed description

At the moment when there are multiple problems in an OpenAPI document, Speccy will only output the first problem. For instance when a component that is being referred to using `$ref` is missing, it'll only output the first instance where that `$ref` is used.

## Context

When fixing these problems requires a build step in another system it is very inconvenient to solve one of these at a time. It would be very nice if speccy would output multiple (or all!) of these problems at once.

In addition when Speccy will be used as a linter inside editors it makes sense to show all problems and not just showing the next one once the first one is fixed.

## Possible implementation

Currently `should` is used to return validation errors. It uses exceptions, which aren't easily composable. It probably requires a lot of work, but all functions should return an array of problems. An alternative is to catch each error and compose a new one when multiple validations are being done in a single function.

**Comment by philsturgeon** [comment]
It’s pretty common for validation errors to be shown one at a time, as the validation can effect the rest of the file. Linting results are wrapped as we can tell you about multiple of those easily enough and a missing description won’t effect the validity of the rest of the document.

I don’t want to send folks multiple validation errors, which cause them to make multiple edits, only for them to find out one or more of those edits were actually incorrect and are no longer relevant now a previous error has been fixed. 

—
Phil Sturgeon

**Comment by bobvanderlinden** [comment]
Yes, I totally agree it isn't always possible. For instance when JSON is not valid, then it will be hard to validate everything inside JSON. However, many times it is possible. When the title of the document is missing it should still be possible to validate individual endpoints. When one endpoint fails to validate it should still be able to validate others.

Is this something that is a desired feature of the library or are you opposed to the entire idea of returning multiple validation errors?

**Comment by philsturgeon** [comment]
To get back to this, yes it would be lovely if possible, but that work would need to be done on `oas-validator` instead of here. https://github.com/Mermade/oas-kit/

If that were to support it, then speccy would be tweaked to surface those multiple errors.
