### ISSUE TITLE
readme doesn't explain "resolve" command

### ISSUE THREAD

**Issue by StephenNay** [wework/speccy#59]
## Detailed description

There is no description of the "resolve" command in the readme file. What does resolve do? What options does it take? From a Phil Sturgeon post on _APIs You Won't Hate_, I gather that resolve "pulls in all the $ref’s to create one mega-file." That's the function that I'm interested in, and it would be nice if the readme said at least a little bit about it to save me the time of downloading it and trying it just to find out. I'm sure it's great, but a description would be nice.

**Comment by philsturgeon** [comment]
Better resolved in https://github.com/wework/speccy/pull/87
