### ISSUE TITLE
Use speccy/lib/loader as module?

### ISSUE THREAD

**Issue by tonious** [wework/speccy#62]
## Detailed description

I have a project where I'm defining specs separately from code, using OpenAPI and JSON-Schema (thank you Speccy 0.6!).  Using speccy to resolve includes and run redoc works very nicely.  However, I'd like to use the resolved and loaded spec as an object, so I can use it directly in code.  For example, providing documentation for endpoints, validating input, and so on.

Where I have behaviour that I can define as part of spec, I want to be able to use that spec to implement the behaviour instead of duplicating the configuration.

## Context

Right now, I'm doing this by directly requiring  `speccy/lib/loader`

```javascript
'use strict';

const path = require('path');
const loader = require('speccy/lib/loader');

module.exports = () => loader.readOrError(
    path.join(__dirname, 'app.spec.json'),
    {
        jsonSchema: true,
        resolve: true
    }
)
```

## Possible implementation

At this point, I don't have any real code changes or features to request.  I'm just curious about how stable this approach will be over time.  Are these internals expected to change?

Or conversely, if this is a good idea, should I submit some documentation? ;)

**Comment by philsturgeon** [comment]
At this point I don't have any plans to change it, and I'm glad it's useful to you. I suppose if you put it in the README then I'm a bit more obliged to a) not change things, or b) be very clear about changes if they happen.

**Comment by tonious** [comment]
👍 

I'll throw something together.
