### ISSUE TITLE
URI fragments and --json-schema option

### ISSUE THREAD

**Issue by mesca** [wework/speccy#70]
The `--json-schema` is exactly what I need, but it does not work well with JSON pointers.

Here is a minimal example:

def.json:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "foobar": {
      "type": ["string", "null"]
    }
  }
}
```

test.yaml:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
components:
  schemas:
    $ref: ./def.json
paths:
  /:
    get:
      parameters:
        - name: foobar
          in: query
          schema:
            $ref: ./def.json#/definitions/foobar
```

Output of `speccy resolve test.yaml -j`:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
components:
  schemas:
    definitions:
      foobar:
        type:
          - string
          - 'null'
paths:
  /:
    get:
      parameters:
        - name: foobar
          in: query
          schema:
            type:
              - string
              - 'null'
```

It should render a nullable, but the type is left untouched.

**Comment by philsturgeon** [comment]
What version are you using? (There's a reason we ask for that in the issue template!) 

This was fixed in 0.7.0 so if you're on a lesser version you'll want to upgrade.

**Comment by mesca** [comment]
I'm using 0.7.0.

**Comment by philsturgeon** [comment]
Ok! That rules that out then, thank you. If you check the test cases you’ll see that $ref nullable does work fine, so something else is going on here.

Can you make a new test case from your example, and try debugging a few things? Console log goes a long way! I’m not gonna get to look at this until tomorrow now.

**Comment by mesca** [comment]
[This](https://github.com/wework/speccy/blob/1ffa57a3053c1059d7db6f5f91d71fe74f8e79a4/test/loader.test.js#L88) test case works as expected. The problem appears when `$ref` has an URI fragment, which is not the case in [openapi.yaml](https://github.com/wework/speccy/blob/1ffa57a3053c1059d7db6f5f91d71fe74f8e79a4/test/samples/json-schema/openapi.yaml).

**Comment by philsturgeon** [comment]
Let's carry on this discussion at #73. :)
