### ISSUE TITLE
Different exit codes for different errors

### ISSUE THREAD

**Issue by greg0ire** [wework/speccy#71]
## Detailed description
Right now, it looks like Speccy always exits with 1, regardless of whether a validation error or a lint error occurs. I think it could be handy to have it exit with 1 when there are only validation errors, with 2 if there are only lint errors, and with 3 if there are both.

## Context

I'm planning to use this in CI and am unsure yet if I will respect all lint errors, particularly the one about the `contact` object.
I would use this to make comparisons with the exit code, to make the CI fail exactly when I want it to.

How can it benefit other users? Other users with old, valid definitions that don't pass linting would be able to start using this tool in CI, and slowly make their schema valid

## Possible implementation

Store one integer (0 or 1) for each problem type, multiply one of them by 2, then sum

## Your environment

Not relevant I think.

**Comment by philsturgeon** [comment]
Based on your use case, I think you could simply use the —skip option to pass in rules you don’t care about.

I have considered different failure modes in the past but honestly if you just want validation there are validatiors out there. If you want linting but you don’t want certain rules then make your own rules files or use the built in ones and skip the bits you don’t want.

I’m not sure we need to make a third approach just yet. :)

**Comment by philsturgeon** [comment]
Thank you! :)
