### ISSUE TITLE
component referencing doesn't work across different files

### ISSUE THREAD

**Issue by ingoclaro** [wework/speccy#84]
## Detailed description

I found the following bug when defining components in a separate file, they don't show up with speccy.

openapi.yaml:
```
---
openapi: 3.0.0
info:
  version: 1.0.0
  title: OpenAPI Ref Example

components:
  schemas:
    myobject:
      type: object
      properties:
        a:
          description: property a
          type: string
        b:
          type: number

paths:
  /a:
    $ref: './a.yaml'

  /b:
    post:
      summary: b
      parameters:
        - $ref: './parameters.yaml#/foo'
      responses:
        '405':
          description: Invalid input

  /c:
    $ref: './c.yaml'
```

c.yaml:
```
post:
  summary: c
  parameters:
    - $ref: './parameters.yaml#/foo'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/myobject'
  responses:
    '405':
      description: Invalid input
```

Rendered result:
![redoc](https://user-images.githubusercontent.com/1280277/40862375-28df6a10-65a1-11e8-9136-8fec43f63378.jpg)

If I move the definition of `c` inline (without the $ref: './c.yaml' ) then it's shown correctly.

## Your environment

* Node Version: v9.7.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): OSX el capitan (10.11.6)

**Comment by ingoclaro** [comment]
I noticed that just commenting [this line](https://github.com/wework/speccy/blob/master/lib/resolver.js#L57) out fixes the problem and all tests pass:

**Comment by philsturgeon** [comment]
This looks like c.yaml is trying to reference #/components from a different file, which is invalid usage of $ref. That # is an anchor which separates a filepath from the local aspect of the pointer. If /components does not exist in c.yaml then... correct, it doesn’t exist.

—
Phil Sturgeon
