### ISSUE TITLE
Feature: allow speccy to watch and resolve

### ISSUE THREAD

**Issue by devjack** [wework/speccy#85]
## Detailed description

Many cli tools allow you to `-w` watch changes to a specified file and re-run execution for the differences. 

I propose adding a `-w` flag to speccy allowing similar behaviour.

```
speccy resolve -w -v -j myspec.yml -o ~/elsewhere/projects/specs/myapi.yml
```

## Context

Proposed documentation workflow is roughly:

1. Define a spec + schema
2. 'resolve' the spec into an output asset. Publish (somewhere)
3. External docs  (static site, using redoc to inline API specs)

This workflow would allow a smoother edit-and-preview workflow for the above toolchain.

Current toolchain uses speccy 0.7.2+

**Comment by devjack** [comment]
# Alternative / Workaround

It is possible to set this up as an npm run command using `npm-watch`:

```
{
  ...
  "watch": {
    "test": {
      "patterns": ["**/*"]
    }
  },
  "scripts": {
    "test": "node_modules/.bin/speccy lint myspec.yml -j",
    "watch": "npm-watch"
  },
  "devDependencies": {
    "npm-watch": "^0.3.0",
    "speccy": "^0.7.2"
  }
  ...
}
```

This can then be invoked as `npm run watch` as part of your in-IDE editing.

This could then limit this feature request to "Provide a useful progress bar for # of lint failures" so that npm-watch is able to give you an idea of how far through fixing things are you.

**Comment by bburtin** [comment]
Is this really a common CLI feature?  Sounds more like a job for an external utility that watches for changes to a file, as opposed to something that's embedded into Speccy.

**Comment by philsturgeon** [comment]
Agreed with @bburtin, this was a nice idea but it's a big effort and will distract from other priorities. If somebody finds a nice simple way to bake it in then yay, otherwise it's not going to happen for a long time.

**Comment by grantcarthew** [comment]
I've added a pull request to add watch details to the README file.

https://github.com/wework/speccy/pull/362
