### ISSUE TITLE
Document resolve command usage

### ISSUE THREAD

**Issue by jblazek** [wework/speccy#86]
The readme doesn't have a section for the `resolve` command.

## Detailed description

The usage sections cover the `lint` and and `serve` commands, but not `resolve`. I started using a different utility to do this operation, since it wasn't clear that speccy could also do this.

## Context

This would make it more clear about the full capabilities of this tool.

**Comment by philsturgeon** [comment]
@jblazek can you write this one up? I'm working on #54 this sprint.

**Comment by jblazek** [comment]
I'm not going to be able to get to it for a while, I actually tried calling `speccy resolve spec.yaml`, and it seemed like it didn't escape my external ref. I'll have to try a simplified example to see if it's a bug or something I'm doing wrong.

I'm currently using a different utility to do bundling, https://github.com/moon0326/swagger-ui-watcher.

**Comment by philsturgeon** [comment]
Fair enough! Just did it over in #87. 

It _does_ resolve external references so long as you're using them according to the specification. Some people have got a little creative (questionaly valid) and they've experienced problems with that.
